name = "my-hugo-site"
type = "javascript"  # or "webpack" if you're using webpack

account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2024-11-19"
[env.production]
route = "nikd.co/*"
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "my-hugo-site-bucket"
preview_bucket_name = "my-hugo-site-bucket-preview"
[site]
bucket = "./public"  # Directory containing static files
entry-point = "./"  # Directory containing worker script
[vars]
GREETING = "Hello, World!"